config/routes.rb
Rails.application.routes.draw do


  resources :password_resets, except: [:index, :destroy]

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, confirmation: true
  has_secure_password
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :find_user, only: [:edit, :update]

  def find_user
    @user = User.find_by!(password_reset_token: (params[:id]))
  end

  def new
  end

  def edit
  end

  def create
    user = User.find_by(email: params[:email])
    user.send_password_reset
    redirect_to root_url, notice: 'Email sent'
  end

  def update
    if @user.password_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, notice: "Password expired"
    elsif @user.update_attributes(user_params)
      redirect_to root_url, notice: "Password has been reset"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWeekend3WlasnaAutoryzacjaTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, url: password_reset_path(params[:id]) do |f| %>

    <% if @user.errors.any? %>
     <div class="error_messages" %>
       <h2>Form is invalid</h2>
       <ul>
         <%= @user.errors.full.messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
       </ul>
    <% end %>
     </div>

    <div class="field" %>
      <%= f.label :password%>
      <%= f.password_field :password %>
    </div>
<div class="field" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
    <div class="actions">
      <%= f.submit "Update Password" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path do %>

    <div class ="field">
      <%= label_tag :email %>
      <%= text_field_tag :email, params[:email] %>
    </div>
    <div class="actions">
      <%= submit_tag "Reset password" %>
    </div>

<% end %>